name=Thermocouple
version=1.0.0
author=Nguyen Trong Thuan
maintainer=thuanproexp@gmail.com
sentence=Thermocouple wrapper using OneWire and DallasTemperature.
paragraph=This library provides a simple class to initialize and read temperature data from DallasTemperature-compatible sensors using OneWire.
category=Sensors
url=https://github.com/Thanosproll1/CDE4301
architectures=*
